services:
  postgres:
    image: postgres:16-alpine
    container_name: tactix-postgres
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tactix-network

  api:
    container_name: tactix-api
    restart: unless-stopped
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    env_file:
      - ./apps/api/.env.development
    environment:
      NX_DAEMON: 'true'
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: '1000'
    ports:
      - '5500:5500'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - nx_cache:/usr/src/app/.nx
    networks:
      - tactix-network

  redis:
    image: redis:alpine
    container_name: tactix-redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tactix-network

networks:
  tactix-network:
    driver: bridge

volumes:
  postgres_data:
  nx_cache:
