/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrendsIndexRouteImport } from './routes/trends/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RegionsIndexRouteImport } from './routes/regions/index'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as PlaybookIndexRouteImport } from './routes/playbook/index'
import { Route as PbeIndexRouteImport } from './routes/pbe/index'
import { Route as MetaIndexRouteImport } from './routes/meta/index'
import { Route as MatchIndexRouteImport } from './routes/match/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as MetaCompIdRouteImport } from './routes/meta/$compId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsIndexRoute = TrendsIndexRouteImport.update({
  id: '/trends/',
  path: '/trends/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsIndexRoute = RegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookIndexRoute = PlaybookIndexRouteImport.update({
  id: '/playbook/',
  path: '/playbook/',
  getParentRoute: () => rootRouteImport,
} as any)
const PbeIndexRoute = PbeIndexRouteImport.update({
  id: '/pbe/',
  path: '/pbe/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaIndexRoute = MetaIndexRouteImport.update({
  id: '/meta/',
  path: '/meta/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIndexRoute = MatchIndexRouteImport.update({
  id: '/match/',
  path: '/match/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaCompIdRoute = MetaCompIdRouteImport.update({
  id: '/meta/$compId',
  path: '/meta/$compId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/meta/$compId': typeof MetaCompIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/match/': typeof MatchIndexRoute
  '/meta/': typeof MetaIndexRoute
  '/pbe/': typeof PbeIndexRoute
  '/playbook/': typeof PlaybookIndexRoute
  '/player/': typeof PlayerIndexRoute
  '/regions/': typeof RegionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/trends/': typeof TrendsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/meta/$compId': typeof MetaCompIdRoute
  '/jobs': typeof JobsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/match': typeof MatchIndexRoute
  '/meta': typeof MetaIndexRoute
  '/pbe': typeof PbeIndexRoute
  '/playbook': typeof PlaybookIndexRoute
  '/player': typeof PlayerIndexRoute
  '/regions': typeof RegionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/stats': typeof StatsIndexRoute
  '/trends': typeof TrendsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/meta/$compId': typeof MetaCompIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/match/': typeof MatchIndexRoute
  '/meta/': typeof MetaIndexRoute
  '/pbe/': typeof PbeIndexRoute
  '/playbook/': typeof PlaybookIndexRoute
  '/player/': typeof PlayerIndexRoute
  '/regions/': typeof RegionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/trends/': typeof TrendsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/meta/$compId'
    | '/jobs/'
    | '/logs/'
    | '/match/'
    | '/meta/'
    | '/pbe/'
    | '/playbook/'
    | '/player/'
    | '/regions/'
    | '/settings/'
    | '/sign-in/'
    | '/sign-up/'
    | '/stats/'
    | '/trends/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/meta/$compId'
    | '/jobs'
    | '/logs'
    | '/match'
    | '/meta'
    | '/pbe'
    | '/playbook'
    | '/player'
    | '/regions'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/stats'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/meta/$compId'
    | '/jobs/'
    | '/logs/'
    | '/match/'
    | '/meta/'
    | '/pbe/'
    | '/playbook/'
    | '/player/'
    | '/regions/'
    | '/settings/'
    | '/sign-in/'
    | '/sign-up/'
    | '/stats/'
    | '/trends/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  MetaCompIdRoute: typeof MetaCompIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  MatchIndexRoute: typeof MatchIndexRoute
  MetaIndexRoute: typeof MetaIndexRoute
  PbeIndexRoute: typeof PbeIndexRoute
  PlaybookIndexRoute: typeof PlaybookIndexRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
  RegionsIndexRoute: typeof RegionsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  TrendsIndexRoute: typeof TrendsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends/': {
      id: '/trends/'
      path: '/trends'
      fullPath: '/trends/'
      preLoaderRoute: typeof TrendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/': {
      id: '/regions/'
      path: '/regions'
      fullPath: '/regions/'
      preLoaderRoute: typeof RegionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/player'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/': {
      id: '/playbook/'
      path: '/playbook'
      fullPath: '/playbook/'
      preLoaderRoute: typeof PlaybookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pbe/': {
      id: '/pbe/'
      path: '/pbe'
      fullPath: '/pbe/'
      preLoaderRoute: typeof PbeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/': {
      id: '/meta/'
      path: '/meta'
      fullPath: '/meta/'
      preLoaderRoute: typeof MetaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/': {
      id: '/match/'
      path: '/match'
      fullPath: '/match/'
      preLoaderRoute: typeof MatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/$compId': {
      id: '/meta/$compId'
      path: '/meta/$compId'
      fullPath: '/meta/$compId'
      preLoaderRoute: typeof MetaCompIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  MetaCompIdRoute: MetaCompIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  MatchIndexRoute: MatchIndexRoute,
  MetaIndexRoute: MetaIndexRoute,
  PbeIndexRoute: PbeIndexRoute,
  PlaybookIndexRoute: PlaybookIndexRoute,
  PlayerIndexRoute: PlayerIndexRoute,
  RegionsIndexRoute: RegionsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  TrendsIndexRoute: TrendsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
