/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrendsIndexRouteImport } from './routes/trends/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as RegionsIndexRouteImport } from './routes/regions/index'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as MetaIndexRouteImport } from './routes/meta/index'
import { Route as MatchIndexRouteImport } from './routes/match/index'
import { Route as MetaCompIdRouteImport } from './routes/meta/$compId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsIndexRoute = TrendsIndexRouteImport.update({
  id: '/trends/',
  path: '/trends/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsIndexRoute = RegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaIndexRoute = MetaIndexRouteImport.update({
  id: '/meta/',
  path: '/meta/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIndexRoute = MatchIndexRouteImport.update({
  id: '/match/',
  path: '/match/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaCompIdRoute = MetaCompIdRouteImport.update({
  id: '/meta/$compId',
  path: '/meta/$compId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meta/$compId': typeof MetaCompIdRoute
  '/match/': typeof MatchIndexRoute
  '/meta/': typeof MetaIndexRoute
  '/player/': typeof PlayerIndexRoute
  '/regions/': typeof RegionsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/trends/': typeof TrendsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meta/$compId': typeof MetaCompIdRoute
  '/match': typeof MatchIndexRoute
  '/meta': typeof MetaIndexRoute
  '/player': typeof PlayerIndexRoute
  '/regions': typeof RegionsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/trends': typeof TrendsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meta/$compId': typeof MetaCompIdRoute
  '/match/': typeof MatchIndexRoute
  '/meta/': typeof MetaIndexRoute
  '/player/': typeof PlayerIndexRoute
  '/regions/': typeof RegionsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/trends/': typeof TrendsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meta/$compId'
    | '/match/'
    | '/meta/'
    | '/player/'
    | '/regions/'
    | '/stats/'
    | '/trends/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meta/$compId'
    | '/match'
    | '/meta'
    | '/player'
    | '/regions'
    | '/stats'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/meta/$compId'
    | '/match/'
    | '/meta/'
    | '/player/'
    | '/regions/'
    | '/stats/'
    | '/trends/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetaCompIdRoute: typeof MetaCompIdRoute
  MatchIndexRoute: typeof MatchIndexRoute
  MetaIndexRoute: typeof MetaIndexRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
  RegionsIndexRoute: typeof RegionsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  TrendsIndexRoute: typeof TrendsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends/': {
      id: '/trends/'
      path: '/trends'
      fullPath: '/trends/'
      preLoaderRoute: typeof TrendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/': {
      id: '/regions/'
      path: '/regions'
      fullPath: '/regions/'
      preLoaderRoute: typeof RegionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/player'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/': {
      id: '/meta/'
      path: '/meta'
      fullPath: '/meta/'
      preLoaderRoute: typeof MetaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/': {
      id: '/match/'
      path: '/match'
      fullPath: '/match/'
      preLoaderRoute: typeof MatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/$compId': {
      id: '/meta/$compId'
      path: '/meta/$compId'
      fullPath: '/meta/$compId'
      preLoaderRoute: typeof MetaCompIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetaCompIdRoute: MetaCompIdRoute,
  MatchIndexRoute: MatchIndexRoute,
  MetaIndexRoute: MetaIndexRoute,
  PlayerIndexRoute: PlayerIndexRoute,
  RegionsIndexRoute: RegionsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  TrendsIndexRoute: TrendsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
